### ISSUE TITLE
Left-brackets '[' being stripped from NXOS output in Netmiko '2.3.0'

### ISSUE THREAD

**Issue by jesse-mcgraw** [ktbyers/netmiko#1100]
[ characters are being removed from NXOS output and replaced with CR/LF

For example, expected output:

```
IP Route Table for VRF "test"
'*' denotes best ucast next-hop
'**' denotes best mcast next-hop
'[x/y]' denotes [preference/metric]
'%<string>' in via output denotes VRF <string>

10.0.0.1/32, ubest/mbest: 1/0
    *via 10.0.0.101, Po0.1, [115/6], 3d08h, isis-65535, L2

```

becomes

```
IP Route Table for VRF "test"
'*' denotes best ucast next-hop
'**' denotes best mcast next-hop
'
x/y]' denotes 
preference/metric]
'%<string>' in via output denotes VRF <string>

10.0.0.1/32, ubest/mbest: 1/0
    *via 10.0.0.101, Po0.1, 
115/6], 3d08h, isis-65535, L2
```

**Comment by ktbyers** [comment]
Can you show your connection arguments that you are using for the Netmiko connection?

**Comment by jesse-mcgraw** [comment]
Nothing too special:

`with ConnectHandler(fast_cli=False, **netmiko_parameters) as conn:`

and

```
- netmiko_parameters:
    host: {{ ROUTER.NAME }}
    device_type: cisco_nxos
    username: {{ user }}
    password: {{ password }}
    global_delay_factor: 1
```
