### ISSUE TITLE
is there demand for a yaml runbook wrapper, which automates netmiko command calls?

### ISSUE THREAD

**Issue by slieberth** [ktbyers/netmiko#225]
Hi Kirk,

first of all, many thanks for providing / maintaining netmiko - great tool ...
second, this is actually not an issue, but a question/post:

I am involved in test scenario, which I want to automate as much as possible. I use netmiko as I have to use ssh with(user/password) -  I think ansible or napalm do require ssh-keys, which is not an option in my test infrastructure.  

I have developed a yaml runbook wrapper, which automates netmiko command calls, also it provides some features for test-automation:
- I use textFSM to parse/verify the CLI responses. This is used to check CLI output for values, parameters
- the tools record/store the output of the CLI commands in files, so it easy to track test values for each step.

some questions to you:
Was there already an approach for an netmiko runbook?
Do you think this is helpful for others?

if yes, I would can post the python file on github.

greetings from Berlin
Stefan

```
config:
  name: TC99
  version: v1
  author: lieberth
  date: 12-06-2016
  workingDir: ./Test/JUNOS151
  cliIni:
    juniper: 
      - set cli screen-length 0
    cisco: 
      - terminal length 0
  steps:
    - config:
        name: set-system-altitute-to-3000
        device: 10.10.10.10
        vendor: juniper
        user: secret
        password: secret
        commands: 
          - set system location altitude 3000
    - check:
        name: check-system-altitute-3000
        device: 10.10.10.10
        vendor: juniper
        user: secret
        password: secret
        command: show configuration system location | display set
        textFSM: |
          Value Required P0 (\S+)
          
          Start
            ^set system location altitude ${P0} -> Record
          
          End
        outputCheckResult: [['3000']]
    - sleep:
        name: 5-secs-break
        duration:   5
    - break:
        name: user-input-required-to-continue
    - config:
        name: del-altitute
        device: 10.10.10.10
        vendor: juniper
        user: secret
        password: secret
        commands: 
          - del system location altitude 3000
    - check:
        name: check-system-altitute-none
        device: 10.10.10.10
        vendor: juniper
        user: secret
        password: secret
        command: show configuration system location | display set
        textFSM: |
          Value Required P0 (\S+)
          
          Start
            ^set system location altitude ${P0} -> Record
          
          End
        outputCheckResult: []
    - record:
        name: record-commands
        device: 10.10.10.10
        vendor: juniper
        user: secret
        password: secret
        commands: 
          - show version"
          - show configuration protocols bgp group grp_ias_isp_eu neighbor 20.99.99.25 | display set
          - show bgp neighbor 20.99.99.25
          - show bgp summary group grp_ias_isp_eu
          - show route advertising-protocol bgp 20.99.99.25 81.7.219.0/24 detail
```
