### ISSUE TITLE
File upload using ansible modul cisco_file_transfer.py failes on busy ios devices

### ISSUE THREAD

**Issue by ciberp** [ktbyers/netmiko#794]
Hello,

we are using ansible module cisco_file_transfer.py for uploading ios image to cisco devices. On some busy devices we constantly get error "Search pattern never detected". Error is solved if we change max_loops parameter in function remote_md5 from default 1500 to 150000. Can you rise default value, so we no longer need to change this value or is there some better solution to fix this?

```
- name: Copy IOS image to device and test image checksum
  cisco_file_transfer:
    source_file: 'firmware/{{ device_model.image }}'
    dest_file: '{{ device_model.image }}'
    host: '{{ ansible_host }}'
    overwrite: false
    port: 22
    username: '{{ ansible_user }}'
    password: '{{ ansible_ssh_pass }}'
    dest_file_system: '{{ device_model.file_system|default("flash:") }}'
  register: results
```

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 
> IOError: Search pattern never detected in send_command_expect: luni\-mb\-fov\-tsp1\#
> fatal: [luni-mb-fov-tsp1.cpe.arnes.si]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):
>   File \"/tmp/ansible_eOuCBt/ansible_module_cisco_file_transfer.py\", line 84, in <module>
>     main()
>   File \"/tmp/ansible_eOuCBt/ansible_module_cisco_file_transfer.py\", line 74, in main
>     if scp_transfer.verify_file():
>   File \"/opt/virtual_environments/harfa/local/lib/python2.7/site-packages/netmiko/scp_handler.py\", line 298, in verify_file
>     return self.compare_md5()
>   File \"/opt/virtual_environments/harfa/local/lib/python2.7/site-packages/netmiko/scp_handler.py\", line 255, in compare_md5
>     remote_md5 = self.remote_md5()
>   File \"/opt/virtual_environments/harfa/local/lib/python2.7/site-packages/netmiko/scp_handler.py\", line 272, in remote_md5
>     dest_md5 = self.ssh_ctl_chan.send_command(remote_md5_cmd, max_loops=1500)
>   File \"/opt/virtual_environments/harfa/local/lib/python2.7/site-packages/netmiko base_connection.py\", line 1051, in send_command
>     search_pattern))
> IOError: Search pattern never detected in send_command_expect: luni\\-mb\\-fov\\-tsp1\\#
> ", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

> def remote_md5(self, base_cmd='verify /md5', remote_file=None):
>     """Calculate remote MD5 and returns the hash.
> 
>     This command can be CPU intensive on the remote device.
>     """
>     if remote_file is None:
>         if self.direction == 'put':
>             remote_file = self.dest_file
>         elif self.direction == 'get':
>             remote_file = self.source_file
>     remote_md5_cmd = "{} {}/{}".format(base_cmd, self.file_system, remote_file)
>     dest_md5 = self.ssh_ctl_chan.send_command(remote_md5_cmd, max_loops=1500)
>     dest_md5 = self.process_md5(dest_md5)
>     return dest_md5

Regards,
Peter
